grain_list = [
    (0, 'American - Aromatic Malt'),
    (1, 'American - Ashbourne Mild'),
    (2, 'American - Black Barley'),
    (3, 'American - Black Malt'),
    (4, 'American - Blackprinz'),
    (5, 'American - Bonlander Munich'),
    (6, 'American - CaraBrown'),
    (7, 'American - CaraCrystal Wheat Malt'),
    (8, 'American - Caramel / Crystal 10L'),
    (9, 'American - Caramel / Crystal 15L'),
    (10, 'American - Caramel / Crystal 20L'),
    (11, 'American - Caramel / Crystal 30L'),
    (12,  'American - Caramel / Crystal 40L'),
    (13, 'American - Caramel / Crystal 60L'),
    (14, 'American - Caramel / Crystal 75L'),
    (15, 'American - Caramel / Crystal 80L'),
    (16, 'American - Caramel / Crystal 90L'),
    (17, 'American - Caramel / Crystal 120L'),
    (18, 'American - Caramel / Crystal 150L'),
    (19, 'American - Carapils (Dextrine Malt)'),
    (20, 'American - Chocolate'),
    (21, 'American - Dark Chocolate'),
    (22, 'American - Midnight Wheat Malt'),
    (23, 'American - Munich - Light 10L'),
    (24, 'American - Munich - Dark 20L'),
    (25, 'American - Munich - 60L'),
    (26, 'American - Pale 2-Row'),
    (27, 'American - Pale 2-Row - Toasted'),
    (28, 'American - Pale 6-Row'),
    (29, 'American - Pale Ale'),
    (30, 'American - Pilsner'),
    (31, 'American - Red Wheat'),
    (32, 'American - Roasted Barley'),
    (33, 'American - Rye'),
    (34, 'American - Smoked Malt'),
    (35, 'American - Special Roast'),
    (36, 'American - Victory'),
    (37, 'American - Vienna'),
    (38, 'American - Wheat'),
    (39, 'American - White Wheat'),
    (40, 'Belgian - Aromatic'),
    (41, 'Belgian - Biscuit'),
    (42, 'Belgian - Cara 20L'),
    (43, 'Belgian - Cara 45L'),
    (44, 'Belgian - Caramel Pils'),
    (45, 'Belgian - CaraMunich'),
    (46, 'Belgian - CaraVienne'),
    (47, 'Belgian - Chocolate'),
    (48, 'Belgian - De-Bittered Black'),
    (49, 'Belgian - Munich'),
    (50, 'Belgian - Pale Ale'),
    (51, 'Belgian - Pilsner'),
    (52, 'Belgian - Roasted Barley'),
    (53, 'Belgian - Special B'),
    (54, 'Belgian - Unmalted Wheat'),
    (55, 'Belgian - Wheat'),
    (56, 'Canadian - ESB Malt'),
    (57, 'Canadian - Honey Malt'),
    (58, 'Canadian - Munich Dark'),
    (59, 'Canadian - Munich Light'),
    (60, 'Canadian - Pale 2-Row'),
    (61, 'Canadian - Pale Wheat'),
    (62, 'German - Abbey Malt'),
    (63, 'German - Acidulated Malt'),
    (64, 'German - Bohemian Pilsner'),
    (65, 'German - CaraAmber'),
    (66, 'German - CaraAroma'),
    (67, 'German - CaraBelge'),
    (68, 'German - CaraBohemian'),
    (69, 'German - Carafa I'),
    (70, 'German - Carafa II'),
    (71, 'German - Carafa III'),
    (72, 'German - CaraFoam'),
    (73, 'German - CaraHell'),
    (74, 'German - Caramel Pils'),
    (75, 'German - Caramel Wheat'),
    (76, 'German - CaraMunich I'),
    (77, 'German - CaraMunich II'),
    (78, 'German - CaraMunich III'),
    (79, 'German - Carapils'),
    (80, 'German - CaraRed'),
    (81, 'German - Chocolate Rye'),
    (82, 'German - Chocolate Wheat'),
    (83, 'German - Dark Munich'),
    (84, 'German - Dark Wheat'),
    (85, 'German - De-Husked Caraf I'),
    (86, 'German - De-Husked Caraf II'),
    (87, 'German - De-Husked Caraf III'),
    (88, 'German - Floor-Malted Bohemian Pilsner'),
    (89, 'German - Floor-Malted Bohemian Pilsner Dk'),
    (90, 'German - Floor-Malted Bohemian Wheat'),
    (91, 'German - Kolsch'),
    (92, 'German - Melanoidin'),
    (93, 'German - Munich Dark'),
    (94, 'German - Munich Light'),
    (95, 'German - Pale Ale'),
    (96, 'German - Pale Wheat'),
    (97, 'German - Pilsner'),
    (98, 'German - Rye'),
    (99, 'German - Smoked Malt'),
    (100, 'German - Spelt Malt'),
    (101, 'German - Vienna'),
    (102, 'German - Wheat Malt'),
    (103, 'United Kingdom - Amber'),
    (104, 'United Kingdom - Black Patent'),
    (105, 'United Kingdom - Brown'),
    (106, 'United Kingdom - Cara Malt'),
    (107, 'United Kingdom - Carastan (30/37)'),
    (108, 'United Kingdom - Carastan Light (15L)'),
    (109, 'United Kingdom - Chocolate'),
    (110, 'United Kingdom - Coffee Malt'),
    (111, 'United Kingdom - Crystal 15L'),
    (112, 'United Kingdom - Crystal 30L'),
    (113, 'United Kingdom - Crystal 45L'),
    (114, 'United Kingdom - Crystal 50L'),
    (115, 'United Kingdom - Crystal 60L'),
    (116, 'United Kingdom - Crystal 70L'),
    (117, 'United Kingdom - Crystal 90L'),
    (118, 'United Kingdom - Crystal 140L'),
    (119, 'United Kingdom - Crystal Rye'),
    (120, 'United Kingdom - Dextrine Malt'),
    (121, 'United Kingdom - Dark Crystal 80L'),
    (122, 'United Kingdom - Extra Dark Crystal 120L'),
    (123, 'United Kingdom - Extra Dark Crystal 160L'),
    (124, 'United Kingdom - Golden Naked Oats'),
    (125, 'United Kingdom - Golden Promise'),
    (126, 'United Kingdom - Halcyon'),
    (127, 'United Kingdom - Lager'),
    (128, 'United Kingdom - Malted Naked Oats'),
    (129, 'United Kingdom - Maris Otter Pale'),
    (130, 'United Kingdom - Mild'),
    (131, 'United Kingdom - Munich'),
    (132, 'United Kingdom - Oat Malt'),
    (133, 'United Kingdom - Optic'),
    (134, 'United Kingdom - Pale 2-Row'),
    (135, 'United Kingdom - Pale Chocolate'),
    (136, 'United Kingdom - Pearl'),
    (137, 'United Kingdom - Peated Malt'),
    (138, 'United Kingdom - Pilsen'),
    (139, 'United Kingdom - Roasted Barley'),
    (140, 'United Kingdom - Wheat')]
