hop_list = [
    (0, "Admiral"),
    (1, "Ahtanum"),
    (2, "Amarillo Gold"),
    (3, "Aquila"),
    (4, "Banner"),
    (5, "Bramling Cross"),
    (6, "Brewers Gold"),
    (7, "Bullion"),
    (8, "Cascade"),
    (9, "Centennial"),
    (10, "Challenger"),
    (11, "Chinook"),
    (12, "Cluster"),
    (13, "Columbia"),
    (14, "Columbus(Tomahawk)"),
    (15, "Comet"),
    (16, "Crystal"),
    (17, "Eroica"),
    (18, "First Gold"),
    (19, "Fuggles"),
    (20, "Galena"),
    (21, "Glacier"),
    (22, "Goldings B. C."),
    (23, "Goldings East Kent(EK)"),
    (24, "Green Bullet"),
    (25, "Hallertauer"),
    (26, "Hallertauer Hersbrucker"),
    (27, "Hallertauer Mittelfrueh"),
    (28, "Hallertauer New Zealand"),
    (29, "Herald"),
    (30, "Horizon"),
    (31, "Liberty"),
    (32, "Lublin"),
    (33, "Magnum"),
    (34, "Mt. Hood"),
    (35, "Northdown"),
    (36, "Northern Brewer"),
    (37, "Nugget"),
    (38, "Orion"),
    (39, "Pacific Gem"),
    (40, "Pearle"),
    (41, "Phoenix"),
    (42, "Pilgrim"),
    (43, "Pioneer"),
    (44, "Pride of Ringwood"),
    (45, "Progress"),
    (46, "Saaz"),
    (47, "Santiam"),
    (48, "Select Spalt"),
    (49, "Southern Cross"),
    (50, "Spalter"),
    (51, "Sterling"),
    (52, "Sticklebract"),
    (53, "Strisselspalt"),
    (54, "Styrian Goldings"),
    (55, "Sun"),
    (56, "Super Alpha"),
    (57, "Target"),
    (58, "Tettnang"),
    (59, "Tradition"),
    (60, "Ultra"),
    (61, "Vanguard"),
    (62, "Warrior"),
    (63, "Whitbread Golding Var(WGV)"),
    (64, "Willamette"),
    (65, "Zeus")
    ]
