"""empty message

Revision ID: 1f2ed02f645b
Revises: None
Create Date: 2015-03-24 23:08:36.733839

"""

# revision identifiers, used by Alembic.
revision = '1f2ed02f645b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
