"""empty message

Revision ID: 40d016e04fff
Revises: None
Create Date: 2015-03-24 22:38:32.254468

"""

# revision identifiers, used by Alembic.
revision = '40d016e04fff'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipment_profile', '_fermenterLoss')
    op.drop_column('equipment_profile', '_trubLoss')
    op.drop_column('equipment_profile', '_equipmentLoss')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipment_profile', sa.Column('_equipmentLoss', sa.INTEGER(), nullable=True))
    op.add_column('equipment_profile', sa.Column('_trubLoss', sa.INTEGER(), nullable=True))
    op.add_column('equipment_profile', sa.Column('_fermenterLoss', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###
