"""empty message

Revision ID: 4e7e1fbca3ce
Revises: 545059263e09
Create Date: 2015-03-02 20:45:58.502356

"""

# revision identifiers, used by Alembic.
revision = '4e7e1fbca3ce'
down_revision = '545059263e09'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('_trub_loss', mysql.INTEGER(), nullable=True),
    sa.Column('_equipment_loss', mysql.INTEGER(), nullable=True),
    sa.Column('_fermenter_loss', mysql.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipment_profile')
    ### end Alembic commands ###
