"""empty message

Revision ID: 545059263e09
Revises: None
Create Date: 2015-03-02 18:57:18.548377

"""

# revision identifiers, used by Alembic.
revision = '545059263e09'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
